### ISSUE TITLE
実は，吊り眉毛になるらしいです．

### ISSUE THREAD

**Issue by m-tsuru** [yude/gyutto-face#1]
![image](https://github.com/yude/gyutto-face/assets/147146974/fdf29965-5ccc-4667-bfc2-c3ad8718f5cf)

https://github.com/yude/gyutto-face/blob/67e859762e2acc29cd3a5e8afd327bad0332174b/src/app/components/Canvas.tsx#L252

ここを -13 とすることで対応できます．
なお，-100% を指定できたほうがいいかもしれません

**Comment by yude** [comment]
Fixed in 6391669bafcee6ad8bc4576a42963e16db23b37c
